#<!--extent.reporter.spark.start=true
#<!--extent,reporter.spark.out=output/SparkReport/Spark.html
#<!--extent.reporter.spark.start=true
<!--extent.reporter.spark.out = Report/Spark.html

<!--screenshot.dir=Screenshots/
<!--screenshot.rel.path=../Screenshots/
<!--basefolder.name=output/SparkReport
<!--basefolder.datetimepattern=d-MMM-YY HH-mm-ss

extent.reporter.spark.start=true
extent.reporter.spark.out=eCommerce-SparkReport/eTools-Spark-Test-Report.html
extent.reporter.pdf.start=true
extent.reporter.pdf.out=eCommerce-PDFReport/eCommerce-PDF-Test-Report.pdf
screenshot.dir=extent-report/screenshots
screenshot.rel.path=../

basefolder.name=extent-reports/extent-report
basefolder.datetimepattern=MMM-dd-yyyy-HH_mm
extent.reporter.spark.config.documentTitle=eCommerce Cucumber Test Report
extent.reporter.spark.config.reportName=eCommerce Cucumber Test Results