name: Manual Allure Execution

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: "dev"
      url:
        required: true
        default: "https://rahulshettyacademy.com/client"
      browser:
        required: true
        default: "chrome"
      tags:
        required: true
        default: "@Regression"

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Validate Credentials
        run: |
          if [ -z "${{ secrets.EMAIL }}" ] || [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "❌ ERROR: EMAIL or PASSWORD secrets not configured in GitHub!"
            exit 1
          fi
          echo "✅ Credentials validated"

      - name: Run Tests
        run: |
          set -e
          mvn clean test \
          -Denv="${{ github.event.inputs.env }}" \
          -Durl="${{ github.event.inputs.url }}" \
          -Dbrowser="${{ github.event.inputs.browser }}" \
          -Dcucumber.filter.tags="${{ github.event.inputs.tags }}" \
          -DEMAIL="${EMAIL}" \
          -DPASSWORD="${PASSWORD}" \
          -DfailIfNoTests=true

      - name: Generate Allure Report
        run: |
          set -e
          mvn allure:report

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
          keep_files: true
          cname: ""
